"""empty message

Revision ID: 5949b0d2471f
Revises: 
Create Date: 2019-11-05 18:21:02.921756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5949b0d2471f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('at_names', sa.String(length=64)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('criticism_html', sa.TEXT(), nullable=True))
    op.add_column('students', sa.Column('body_html', sa.TEXT(), nullable=True))
    op.drop_column('posts', 'time')
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    # ### end Alembic commands ###
